name: 'Hello World'
description: 'Greet someone and record the time'
inputs:
  scan-url:  
    description: 'URL to scan with'
    required: true
    default: 'https://api.metadefender.com/v4//file'
  scan-path:  
    description: 'Files/Folders to scan'
    required: true
    default: ''
  exclude-path:  
    description: 'Do not scan these folders/files'
    required: false
    default: ''
  log-file:  
    description: 'Log Output'
    required: true
    default: ''
  apikey:  
    description: 'APIKey'
    required: false
    default: ''
  fail-build:  
    description: 'Failed the build if found some issue'
    required: false
    default: 1
  show-blocked-file-only:  
    description: 'Show blocked files only'
    required: false
    default: 1
  github-token:  
    description: 'To comment to a PR'
    required: false
    default: 1     
outputs:
  time: # id of output
    description: 'The time we greeted you'
runs:
  using: 'node16'
  main: 'index.js'