name: 'Hello World'
description: 'Greet someone and record the time'
inputs:
  scan-url:  
    description: 'URL to scan with'
    required: true
    default: 'https://api.metadefender.com/v4//file'
  scan-path:  
    description: 'Files/Folders to process'
    required: true
    default: ''
  exclude-path:  
    description: 'Do not process these folders/files'
    required: false
    default: ''
  log-file:  
    description: 'Log Output'
    required: true
    default: ''
  apikey:  
    description: 'APIKey'
    required: false
    default: ''
  fail-build:  
    description: 'Failed the build if found some issue'
    required: false
    default: 1
  show-blocked-file-only:  
    description: 'Show blocked files only'
    required: false
    default: 1
  rule:  
    description: 'Rule name'
    required: false
    default: ''
  private-scan:  
    description: 'Use for MetaDefender Cloud only'
    required: false
    default: 0
  timeout:  
    description: 'Scan timeout per file'
    required: false
    default: 60
  github-token:  
    description: 'To comment to a PR'
    required: false
    default: ''    
outputs:
  time: # id of output
    description: 'The time we greeted you'
runs:
  using: 'node16'
  main: 'index.js'