name: GitHub Actions Demo
on: 
  push:
    branches: [main]

jobs:

  pipeline_scan:
      runs-on: ubuntu-latest
      name: pipeline scan

      steps:
        - name: checkout
          uses: actions/checkout@v2

        - name: install node v16
          uses: actions/setup-node@v1
          with:
            node-version: 16
        
        - name: npm install
          run: npm install
        
        - name: check current folder
          run: ls .
          
        - name: check node_modules
          run: ls node_modules

        - name: Hello world action step
          id: hello
          uses: vlam0120/metadefender-github-action@v13
          with:
            scan-url: 'https://api.metadefender.com/v4/file'
            folder: ${{ github.workspace }}
            logfile: ${{ github.workspace }}/log.txt
            apikey: ${{ secrets.APIKey }}
