name: GitHub Actions Demo
on: 
  push:
    branches: [main]

jobs:

  pipeline_scan:
      runs-on: ubuntu-latest
      name: pipeline scan

      steps:
        - name: checkout
          uses: actions/checkout@v2

        - name: install node v16
          uses: actions/setup-node@v1
          with:
            node-version: 16
        
        - name: npm install
          run: npm install

        - name: Hello world action step
          id: hello
          uses: vlam0120/metadefender-github-action@1.0
          with:
            who-to-greet: 'Mona the Octocat'
